@extends('layouts.app')

@section('title', 'Pembayaran QRIS')

@section('content')
<div class="min-h-screen bg-gray-50">
    <!-- Header -->
    <div class="bg-white shadow">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex justify-between items-center py-6">
                <div>
                    <h1 class="text-3xl font-bold text-gray-900">Pembayaran QRIS</h1>
                    <p class="text-gray-600">Scan QR Code untuk menyelesaikan pembayaran</p>
                </div>
                <div class="flex items-center space-x-2">
                    <div class="w-3 h-3 bg-yellow-400 rounded-full animate-pulse"></div>
                    <span class="text-sm text-gray-600">Menunggu Pembayaran</span>
                </div>
            </div>
        </div>
    </div>

    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <!-- QR Code Section -->
            <div class="bg-white p-8 rounded-lg shadow text-center">
                <h3 class="text-lg font-medium text-gray-900 mb-6">Scan QR Code</h3>
                
                <!-- QR Code Placeholder (In real implementation, this would be generated by payment gateway) -->
                <div class="mx-auto w-64 h-64 bg-gray-100 border-2 border-dashed border-gray-300 rounded-lg flex items-center justify-center mb-6">
                    <div class="text-center">
                        <svg class="mx-auto w-16 h-16 text-gray-400 mb-2" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 10a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1v-6zM14 9a1 1 0 00-1 1v6a1 1 0 001 1h2a1 1 0 001-1v-6a1 1 0 00-1-1h-2z" clip-rule="evenodd"></path>
                        </svg>
                        <p class="text-sm text-gray-500">QR Code akan muncul di sini</p>
                        <p class="text-xs text-gray-400">Dalam implementasi nyata</p>
                    </div>
                </div>
                
                <!-- Payment Instructions -->
                <div class="text-left">
                    <h4 class="font-medium text-gray-900 mb-3">Cara Pembayaran:</h4>
                    <ol class="text-sm text-gray-600 space-y-2">
                        <li class="flex items-start">
                            <span class="flex-shrink-0 w-5 h-5 bg-blue-500 text-white rounded-full text-xs flex items-center justify-center mr-2 mt-0.5">1</span>
                            Buka aplikasi e-wallet atau mobile banking Anda
                        </li>
                        <li class="flex items-start">
                            <span class="flex-shrink-0 w-5 h-5 bg-blue-500 text-white rounded-full text-xs flex items-center justify-center mr-2 mt-0.5">2</span>
                            Pilih menu "Scan QR" atau "QRIS"
                        </li>
                        <li class="flex items-start">
                            <span class="flex-shrink-0 w-5 h-5 bg-blue-500 text-white rounded-full text-xs flex items-center justify-center mr-2 mt-0.5">3</span>
                            Arahkan kamera ke QR Code di atas
                        </li>
                        <li class="flex items-start">
                            <span class="flex-shrink-0 w-5 h-5 bg-blue-500 text-white rounded-full text-xs flex items-center justify-center mr-2 mt-0.5">4</span>
                            Konfirmasi pembayaran pada aplikasi Anda
                        </li>
                    </ol>
                </div>
                
                <!-- Timer -->
                <div class="mt-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
                    <div class="flex items-center justify-center">
                        <svg class="w-5 h-5 text-yellow-600 mr-2" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd"></path>
                        </svg>
                        <span class="text-sm font-medium text-yellow-800">
                            Sisa waktu: <span id="countdown">14:59</span>
                        </span>
                    </div>
                </div>
            </div>

            <!-- Order Details -->
            <div class="bg-white p-6 rounded-lg shadow">
                <h3 class="text-lg font-medium text-gray-900 mb-4">Detail Pesanan</h3>
                
                <!-- Order Number -->
                <div class="bg-gray-50 p-4 rounded-lg mb-4">
                    <div class="flex justify-between items-center">
                        <span class="text-sm font-medium text-gray-700">Order Number:</span>
                        <span class="text-sm font-mono text-gray-900">{{ $orderNumber }}</span>
                    </div>
                </div>
                
                <!-- Items Summary -->
                <div class="space-y-4 mb-6">
                    @foreach($orderDetails['items_by_warung'] as $warungName => $items)
                        <div class="border border-gray-200 rounded-lg p-4">
                            <h4 class="font-medium text-gray-900 mb-2">{{ $warungName }}</h4>
                            <div class="space-y-2">
                                @foreach($items as $item)
                                    <div class="flex justify-between text-sm">
                                        <span class="text-gray-600">{{ $item['menu_name'] }} x{{ $item['quantity'] }}</span>
                                        <span class="text-gray-900">Rp {{ number_format($item['price'] * $item['quantity']) }}</span>
                                    </div>
                                @endforeach
                            </div>
                            <div class="mt-2 pt-2 border-t border-gray-200">
                                <div class="flex justify-between text-sm font-medium">
                                    <span>Subtotal:</span>
                                    <span>Rp {{ number_format(collect($items)->sum(function($item) { return $item['price'] * $item['quantity']; })) }}</span>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
                
                <!-- Total -->
                <div class="border-t border-gray-200 pt-4 mb-6">
                    <div class="flex justify-between text-lg font-medium">
                        <span class="text-gray-900">Total Pembayaran:</span>
                        <span class="text-gray-900">Rp {{ number_format($orderDetails['total_amount']) }}</span>
                    </div>
                </div>
                
                <!-- Status Check -->
                <div class="text-center">
                    <button onclick="checkPaymentStatus()" 
                            class="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition duration-300">
                        Cek Status Pembayaran
                    </button>
                    <p class="text-xs text-gray-500 mt-2">Klik jika pembayaran sudah dilakukan</p>
                </div>
                
                <!-- Demo Payment Button -->
                <div class="mt-4 text-center">
                    <div class="border-t border-gray-200 pt-4">
                        <p class="text-xs text-gray-500 mb-2">Demo Mode - Simulasi Pembayaran:</p>
                        <button onclick="simulatePayment()" 
                                class="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition duration-300 text-sm">
                            Simulasi Pembayaran Berhasil
                        </button>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Help Section -->
        <div class="mt-8 bg-white p-6 rounded-lg shadow">
            <h3 class="text-lg font-medium text-gray-900 mb-4">Butuh Bantuan?</h3>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div class="text-center p-4 border border-gray-200 rounded-lg">
                    <svg class="mx-auto w-8 h-8 text-blue-500 mb-2" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z"></path>
                    </svg>
                    <h4 class="font-medium text-gray-900">Customer Service</h4>
                    <p class="text-sm text-gray-500">0800-1234-5678</p>
                </div>
                
                <div class="text-center p-4 border border-gray-200 rounded-lg">
                    <svg class="mx-auto w-8 h-8 text-green-500 mb-2" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M18 10c0 3.866-3.582 7-8 7a8.841 8.841 0 01-4.083-.98L2 17l1.338-3.123C2.493 12.767 2 11.434 2 10c0-3.866 3.582-7 8-7s8 3.134 8 7zM7 9H5v2h2V9zm8 0h-2v2h2V9zM9 9h2v2H9V9z" clip-rule="evenodd"></path>
                    </svg>
                    <h4 class="font-medium text-gray-900">WhatsApp</h4>
                    <p class="text-sm text-gray-500">+62 812-3456-7890</p>
                </div>
                
                <div class="text-center p-4 border border-gray-200 rounded-lg">
                    <svg class="mx-auto w-8 h-8 text-purple-500 mb-2" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"></path>
                        <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"></path>
                    </svg>
                    <h4 class="font-medium text-gray-900">Email</h4>
                    <p class="text-sm text-gray-500">support@nganteen.com</p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Success Modal -->
<div id="successModal" class="fixed inset-0 bg-gray-600 bg-opacity-50 hidden overflow-y-auto h-full w-full z-50">
    <div class="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
        <div class="mt-3 text-center">
            <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-green-100">
                <svg class="h-6 w-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                </svg>
            </div>
            <h3 class="text-lg font-medium text-gray-900 mt-4">Pembayaran Berhasil!</h3>
            <p class="text-sm text-gray-500 mt-2">Pesanan Anda sedang diproses oleh warung masing-masing.</p>
            <div class="mt-6">
                <a href="{{ route('orders.index') }}" 
                   class="bg-green-600 text-white px-6 py-2 rounded-lg hover:bg-green-700 transition duration-300">
                    Lihat Pesanan Saya
                </a>
            </div>
        </div>
    </div>
</div>

<script>
// Countdown timer
let timeLeft = 15 * 60; // 15 minutes in seconds

function updateCountdown() {
    const minutes = Math.floor(timeLeft / 60);
    const seconds = timeLeft % 60;
    document.getElementById('countdown').textContent = 
        `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
    
    if (timeLeft <= 0) {
        // Payment timeout
        alert('Waktu pembayaran habis. Silakan lakukan checkout ulang.');
        window.location.href = '{{ route('cart.index') }}';
        return;
    }
    
    timeLeft--;
}

// Start countdown
setInterval(updateCountdown, 1000);

// Check payment status
function checkPaymentStatus() {
    fetch(`/payment/status/{{ $orderNumber }}`)
        .then(response => response.json())
        .then(data => {
            if (data.status === 'paid') {
                showSuccessModal();
            } else {
                alert('Pembayaran belum terdeteksi. Silakan coba lagi dalam beberapa saat.');
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Terjadi kesalahan saat mengecek status pembayaran.');
        });
}

// Simulate payment for demo
function simulatePayment() {
    if (confirm('Simulasi pembayaran berhasil?')) {
        fetch(`/payment/simulate/{{ $orderNumber }}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                showSuccessModal();
            } else {
                alert('Simulasi gagal: ' + data.message);
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Terjadi kesalahan');
        });
    }
}

function showSuccessModal() {
    document.getElementById('successModal').classList.remove('hidden');
}

// Auto check payment status every 10 seconds
setInterval(() => {
    fetch(`/payment/status/{{ $orderNumber }}`)
        .then(response => response.json())
        .then(data => {
            if (data.status === 'paid') {
                showSuccessModal();
            }
        })
        .catch(error => {
            console.error('Auto check error:', error);
        });
}, 10000);
</script>
@endsection
